### ISSUE TITLE
Interface weirdness in get_value/1

### ISSUE THREAD

**Issue by filmor** [uwiger/gproc#118]
The following works as expected

    % some process
    gproc:reg({n, l, some_proc}, [], [{value, value}]).

    % some other process
    gproc:get_attribute({n, l, some_proc}, value) =:= value.

The following however doesn't:

    % some process
    gproc:reg({n, l, some_proc}, value).

    % some other process
    gproc:get_value({n, l, some_proc}) =:= value.

The problem is, that `get_value/1` will always look the value up in the current process while `get_attribute/2` will do the smarter thing and look up the attribute on a process depending on the type of the registration, in particular for names it will always give you the attribute value for the current name-holder.

Is this intended behaviour or just an oversight? Would a PR changing `get_value/1` to similar semantics be accepted?

**Comment by uwiger** [comment]
It might be weird behavior, but it is in line with the documentation. I will confess that I can't account for how I was thinking at the time, but here's a try:

* `get_value/1` is only intended for fetching values corresponding to my own reg objects
* `get_value/2` expects me to know which process holds the value, assuming it's an error if this is no longer true. As with `get_value/1`, it expects the requested value to be there.
* `lookup_value/1` does what you are asking for. It exits if you pass it a property, since these are not unique, or if given a name, no such key exists.
* `lookup_values/1` will work for both names and properties, returning all matching `[{Pid,Value}]` entries.

**Comment by filmor** [comment]
Oh, I guess I forgot about `lookup_value/1`, sorry about that. Still, I'm not using `lookup_attribute` and still get the "lookup" behaviour there.

The explanation is fine by me though, from my side this can be closed.
